### Numpy Libray

 - Processing N-Dimensions arrays

In [9]:
import numpy as np
li=[1,2,3,2]
a=np.array(li)
print(a)
print(type(a))

[1 2 3 2]
<class 'numpy.ndarray'>


In [6]:
li=[1,2,3,2,"a"]
a=np.array(li)
a

array(['1', '2', '3', '2', 'a'], dtype='<U11')

In [12]:
b=np.arange(15)
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [14]:
rn = np.random.randint(0,100,size=10)
rn

array([ 9, 46, 34,  1, 73,  3, 33, 27,  1, 36])

In [20]:
m3=np.random.randint(0,2,size=(3,3))
print(m3)
m3[1][2]# in row or coloumn starts with 0,for example 0,0 0,1 0,2

[[1 0 1]
 [1 0 1]
 [1 0 1]]


1

In [30]:
m3=np.random.randint(0,9,size=(2,2))
print(m3)
m3[0][0]

[[5 7]
 [4 4]]


5

In [ ]:
m3=np.random.randint(0,2,size=(2,2))
print(m3)
m3[0][0]

In [34]:
x1 = np.random.randint(10, size=6)  # One-dimensional array
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array
print(x1)
print(x2)
print(x3)

[0 5 2 7 3 4]
[[0 8 1 4]
 [7 5 2 6]
 [0 2 3 8]]
[[[5 7 6 2 9]
  [6 8 4 4 5]
  [8 3 8 2 0]
  [1 7 8 2 4]]

 [[9 6 3 3 9]
  [1 3 2 2 5]
  [2 7 9 7 2]
  [3 4 8 6 4]]

 [[8 0 2 9 3]
  [3 4 2 7 2]
  [3 6 1 1 0]
  [9 3 5 7 6]]]


In [35]:
print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60


In [36]:
print("dtype:", x3.dtype)


dtype: int32


In [37]:
print("itemsize:", x3.itemsize, "bytes")
print("nbytes:", x3.nbytes, "bytes")

itemsize: 4 bytes
nbytes: 240 bytes


In [38]:
x1

array([0, 5, 2, 7, 3, 4])

In [39]:
x1[0]

0

In [40]:
x1[-1]

4

In [41]:
x2

array([[0, 8, 1, 4],
       [7, 5, 2, 6],
       [0, 2, 3, 8]])

In [42]:
x2[0,0]

0

In [43]:
x2[2,-2]

3

In [44]:
x2[0:2,1:2]

array([[8],
       [5]])

In [50]:
y=x2[:-1]
y

array([[0, 8, 1, 4],
       [7, 5, 2, 6]])

In [52]:
z=x2[:-2]
z

array([[0, 8, 1, 4]])

In [49]:
x2


array([[0, 8, 1, 4],
       [7, 5, 2, 6],
       [0, 2, 3, 8]])

In [53]:
x2[:3,:2]

array([[0, 8],
       [7, 5],
       [0, 2]])

In [55]:
x2[:3,::3]

array([[0, 4],
       [7, 6],
       [0, 8]])

In [56]:
x2

array([[0, 8, 1, 4],
       [7, 5, 2, 6],
       [0, 2, 3, 8]])

In [59]:
x2[::-1]

array([[0, 2, 3, 8],
       [7, 5, 2, 6],
       [0, 8, 1, 4]])

In [60]:
x2[::-1,::-1]

array([[8, 3, 2, 0],
       [6, 2, 5, 7],
       [4, 1, 8, 0]])

In [61]:
x2

array([[0, 8, 1, 4],
       [7, 5, 2, 6],
       [0, 2, 3, 8]])

In [62]:
x2[:,2]

array([1, 2, 3])

In [63]:
x2

array([[0, 8, 1, 4],
       [7, 5, 2, 6],
       [0, 2, 3, 8]])

In [65]:
x2[2][0]=9

In [66]:
x2

array([[0, 8, 1, 4],
       [7, 5, 2, 6],
       [9, 2, 3, 8]])

In [67]:
x2_sub_copy = x2[:2, :2].copy()
print(x2_sub_copy)

[[0 8]
 [7 5]]


In [69]:
x2_sub_copy = x2[:2, :4].copy()
print(x2_sub_copy)

[[0 8 1 4]
 [7 5 2 6]]


In [70]:
grid = np.arange(1, 10).reshape((3, 3))
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [72]:
grid = np.arange(1, 10).reshape(3,3)
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [79]:
grid = np.array([[1, 2, 3],
                 [4, 5, 6]])
type(grid)

numpy.ndarray

In [78]:
np.concatenate([grid, grid,grid,grid], axis=0)

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [80]:
grid+grid

array([[ 2,  4,  6],
       [ 8, 10, 12]])

## Pandas
#### Use cases
- Data cleaning
- Data Transformation
- Data Analysis
#### Notations
- series --->single/row series 
- DataFrames --->table format

In [1]:
#Series Example

import pandas as pd

internal1={"s1":21,"s2":18,"s3":23}
internal1=pd.Series(internal1)
internal1



s1    21
s2    18
s3    23
dtype: int64

In [15]:
# DataFrame Example

internal1={"s1":21,"s2":18,"s3":23}
#internal1=pd.Series(internal1)
internal2={"s1":21,"s2":18,"s3":23}
#internal2=pd.Series(internal2)
#internal1

final={"Internal1":internal1,"Internal2":internal2}
final=pd.DataFrame(final)
final

Internal1  Internal2
s1         21         21
s2         18         18
s3         23         23

In [16]:
final['Internal1']


s1    21
s2    18
s3    23
Name: Internal1, dtype: int64

In [14]:
final.values

array([[21, 21],
       [18, 18],
       [23, 23]], dtype=int64)

In [17]:
final.columns

Index(['Internal1', 'Internal2'], dtype='object')

In [18]:
final.values[2]

array([23, 23], dtype=int64)

In [19]:
final.values[2,0]

23

In [20]:
final.values[2][0]

23

In [22]:
for row in final.values:
    print("Internal1- ",row[0],"Internal2-",row[0])

Internal1-  21 Internal2- 21
Internal1-  18 Internal2- 18
Internal1-  23 Internal2- 23


In [23]:
final.values

array([[21, 21],
       [18, 18],
       [23, 23]], dtype=int64)

In [27]:
final.loc[3]=[15,18]
final

Internal1  Internal2
s1         21         21
s2         18         18
s3         15         18
3          15         18

In [28]:
final.loc['s4']=[12,16]

final

Internal1  Internal2
s1         21         21
s2         18         18
s3         15         18
3          15         18
s4         12         16

In [29]:
final.drop(3)

Internal1  Internal2
s1         21         21
s2         18         18
s3         15         18
s4         12         16

In [30]:
final

Internal1  Internal2
s1         21         21
s2         18         18
s3         15         18
3          15         18
s4         12         16

In [33]:
final.values[2,0]=45

final

Internal1  Internal2
s1         21         21
s2         18         18
s3         45         18
3          15         18
s4         12         16

In [34]:
final=final.drop(3)
final

Internal1  Internal2
s1         21         21
s2         18         18
s3         45         18
s4         12         16

In [38]:
final.values[1]=[56,78]
final

Internal1  Internal2
s1         21         21
s2         56         78
s3         45         18
s4         12         16

In [42]:
# Reading CSV file data

import pandas as pd
filepath='DataFiles/Income.csv'
incomedf=pd.read_csv(filepath)

incomedf

GEOID       State   2005   2006   2007   2008   2009   2010   2011  \
0  04000US01     Alabama  37150  37952  42212  44476  39980  40933  42590   
1  04000US02      Alaska  55891  56418  62993  63989  61604  57848  57431   
2  04000US04     Arizona  45245  46657  47215  46914  45739  46896  48621   
3  04000US05    Arkansas  36658  37057  40795  39586  36538  38587  41302   
4  04000US06  California  51755  55319  55734  57014  56134  54283  53367   

    2012   2013  
0  43464  41381  
1  63648  61137  
2  47044  50602  
3  39018  39919  
4  57020  57528

In [44]:
# Extract income of all states in 2013

for row in incomedf.values:
    print(row[1],':',row[-1])

Alabama : 41381
Alaska : 61137
Arizona : 50602
Arkansas : 39919
California : 57528


In [45]:
# Avearge income of Arizona

sum=0
for row in range(2,11):
    sum+=incomedf.values[2][row]
    
sum/len(incomedf.values[2][2:])

47214.77777777778

In [50]:
for row in incomedf.values:
    j=row[-2]+j
l=len(str(row[-2]))
#print(l)
print(j/l)

211559.2


In [53]:
sum=0
for row in incomedf.values:
    sum+=row[-2]
k=len(incomedf.values)

#print(k)
sum/k

50038.8